### PR TITLE
Allow a child selector for the handle

### PR DESCRIPTION
**Pull request by ohcibi**
This makes it possible to select a handle based on a class name inside the
resized component.

### CODE REVIEW

**Comment by RickStrahl** [comment]
Not sure I understand why you would want to limit your selector like this. You can already do what you are asking by using a full DOM selector, so why make things more complicated by having more confusing syntax to provide the selector? 

Also unless I don't understand the code right it looks like you are using `.find()` which will limit you to the child scope - what if you want a selector outside of the child scope?

**Comment by ohcibi** [comment]
@RickStrahl 

There is no limitation at all. `.find()` is **only** used when the selector is prepended by a `>` (as I explained in the readme).

You cannot do that for several elements (like in your example with table columns) without using IDs. See the changes in the tablecolumns plugin. It is not necessary to ask for the selector in the drag event as we can obtain this information right in the beginning when setting up the resizable. Please show me the global selector that would work for the table columns plugin if I'm missing something, but I guess the lack of this selector made you implement the plugin like this (with the drag event).

I was using this syntax as its similar to css and especially scss where you can prepend a selector with `>` in a sub-style like

```scss
.foo {
  > .bar {
  }
}
```

is equal to css `.foo > .bar`.

I was also thinking about an option like `handleIsChild` or so which enables to usage of `.find()` which avoids a special syntax. Do you think thats better?

**Comment by ohcibi** [comment]
@RickStrahl are you still onto this?

**Comment by RickStrahl** [comment]
Ok finally had a chance to take a look at this and this looks good. I didn't understand exactly what you meant initially and this makes sense. Using the`>` relatative syntax might prove useful for other stuff as well.

Thanks.

**Comment by ohcibi** [comment]
Glad I could help

**Pull request merged**
