### PR TITLE
Add possibility to avoid resizing in `onDrag`

### PR DESCRIPTION
**Pull request by ohcibi**
I added this because I needed a way to ensure specific min and max
widths.

There is also a "problem" when the calculated width happens to be
negative, which can lead to shakiness when resizing columns in a fixed
layouts. Generally a negative width should never be set but I'd say this
plugin should not decide this but rather let the user decide it with
this callback as negative widths can be useful for other use cases.

Take your time to see if these changes meet your requirements and don't
hesitate to ask me to update/adjust it.

### CODE REVIEW

**Comment by RickStrahl** [comment]
That looks good. The only thing I would change is the return value from `.ondrag`. I think by default the resizing should still fire and you should explicitly opt out by return `true` (or `false`?)...

**Comment by RickStrahl** [comment]
To be honest though the old code probably addressed this scenario just fine - while the old code set the width and height of the $el, the value would not actually be reflected in the DOM until the event method completed executing. So the call to .onDrag() would actually render in the same event cycle, so only the last value set is really reflected in the DOM. I'm not so sure this is worth the extra code and logic required just to not preassign the value.

**Comment by ohcibi** [comment]
The point of this is not the shakiness when the width is negative. That's just a side-effect. I really wanted to simply opt out of resizing at all; in my case to maintain a certain min width of the current column and the column next to it. While the shakiness is an issue that could indeed be addressed by the plugin's internals, there should simply be a way to tell the plugin, to not call `.width()` at all.

I'll push a patch that will ask for an explicit `false` though.

**Comment by RickStrahl** [comment]
Ah, yes that's something I didn't think about - totally opting out of resizing. 

Ok that works for me!

**Comment by ohcibi** [comment]
@RickStrahl I updated the commit to explicitly check for `false` in order to cancel the resizing. You could merge now

**Comment by RickStrahl** [comment]
Thanks Tobias... updated docs and minor code reformatting.

**Pull request merged**
