### PR TITLE
Add reverse option for RTL support

### PR DESCRIPTION
**Pull request by allmarkedup**
Hi Rick,

First - thanks for this little library. I'm using it on a project and it's working great. However I have a need to support RTL languages (potentially dynamically switched). To support these I switch the order of columns using flexbox. However this then breaks my drag resize JS as it's all flipped around.

To address this issue I've added a `reverse` property to the options object which just flips how the width is calculated. Probably an edge use case but may be useful for others too.

My editor appears to have stripped end-line whitespace which is why the diff looks messier than it should! If that's a problem let me know and I'll redo the PR.

Thanks again!

### CODE REVIEW

**Comment by allmarkedup** [comment]
Ah just realised that the gulp `dist` build task may not have actually had the required effect - It seems to have minified the version that is intended to be unminified? I'll see if I can fix it up at my end.

**Comment by allmarkedup** [comment]
Rick - apologies for the deluge of additional commits. I had a few issues with getting the Gulp build task to match the existing output. I've tweaked it and it seems to be working correctly for me now, but if you'd rather me remove this from the PR please let me know.

**Comment by RickStrahl** [comment]
Thanks Mark. The gulp task is weird because that was the only way I could get the Map file to generate properly. Can you check to see whether the map generates correctly with your updates?

I'll check this out later today. If you made the gulp task work more obviously including the map file I'll be happy because that was causing me a bunch of issues.

**Comment by allmarkedup** [comment]
Ah ok sure, I have not checked that the map was generated correctly. I'll double check it first thing tomorrow (UK time!) and confirm.

I've also just realised that calling this property 'reverse' is not really accurate as in my changes it only switches direction of width resizing, not height. `rtl` may be better? Or perhaps implement it for height too? 

Also,if you think this use case is too obscure to be worth adding then I'm happy to maintain my own fork separately, no worries :-)

**Comment by RickStrahl** [comment]
No this is a good scenario that would be useful to other things as well. Sometimes you might want to resize the left side.

**Comment by allmarkedup** [comment]
Hi again Rick. I've now amended this to expose two options; one for which side to resize the width from and one for the height. Hopefully it is clear enough.

I've also cleaned up the gulp task so that it's generating the sourcemaps for the minified files correctly now. If there is anything else you need just let me know.

**Comment by RickStrahl** [comment]
Thanks the changes to the the resizable look great. The gulp task however, doesn't work right unfortunately. There's a race condition - sometimes it works sometimes it doesn't due to the timing of the copying of files I think. 

I had to revert out the changes you made to the gulp file to the original setup I had.

Thanks.

**Comment by allmarkedup** [comment]
Ok no worries Rick - I should probably know better than try to tinker with another man's build tasks anyway! :-)

Appreciate you merging the other changes in - and thanks again for putting this out there.

**Comment by RickStrahl** [comment]
No by all means. Build process is not my strength and I welcome any feedback on that. In this case I had a hell of a time to get the map to build though which is why the code tasks are a bit wonky :-)

Anyway appreciate the pull request for the drag directions - that's useful.

Aloha.

**Pull request merged**
